// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package chat.server;

public final class TopicImpl_Stub
    extends java.rmi.server.RemoteStub
    implements chat.interfaces.Topic, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_getListenerInfos_0;
    private static java.lang.reflect.Method $method_publishMessage_1;
    
    static {
	try {
	    $method_getListenerInfos_0 = chat.interfaces.Topic.class.getMethod("getListenerInfos", new java.lang.Class[] {});
	    $method_publishMessage_1 = chat.interfaces.Topic.class.getMethod("publishMessage", new java.lang.Class[] {chat.interfaces.Message.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public TopicImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of getListenerInfos()
    public java.util.Collection getListenerInfos()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getListenerInfos_0, null, -4530301582834125511L);
	    return ((java.util.Collection) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of publishMessage(Message)
    public void publishMessage(chat.interfaces.Message $param_Message_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_publishMessage_1, new java.lang.Object[] {$param_Message_1}, 5681189535016467066L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
