// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package chat.server;

public final class TopicServerImpl_Stub
    extends java.rmi.server.RemoteStub
    implements chat.interfaces.TopicServer, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_addListener_0;
    private static java.lang.reflect.Method $method_getTopicInfos_1;
    private static java.lang.reflect.Method $method_removeListener_2;
    private static java.lang.reflect.Method $method_subscribe_3;
    private static java.lang.reflect.Method $method_unsubscribe_4;
    
    static {
	try {
	    $method_addListener_0 = chat.interfaces.TopicServer.class.getMethod("addListener", new java.lang.Class[] {chat.interfaces.ListenerInfo.class, chat.interfaces.MessageListener.class});
	    $method_getTopicInfos_1 = chat.interfaces.TopicServer.class.getMethod("getTopicInfos", new java.lang.Class[] {});
	    $method_removeListener_2 = chat.interfaces.TopicServer.class.getMethod("removeListener", new java.lang.Class[] {chat.interfaces.ListenerInfo.class});
	    $method_subscribe_3 = chat.interfaces.TopicServer.class.getMethod("subscribe", new java.lang.Class[] {chat.interfaces.TopicInfo.class, chat.interfaces.ListenerInfo.class});
	    $method_unsubscribe_4 = chat.interfaces.TopicServer.class.getMethod("unsubscribe", new java.lang.Class[] {chat.interfaces.TopicInfo.class, chat.interfaces.ListenerInfo.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public TopicServerImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of addListener(ListenerInfo, MessageListener)
    public void addListener(chat.interfaces.ListenerInfo $param_ListenerInfo_1, chat.interfaces.MessageListener $param_MessageListener_2)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_addListener_0, new java.lang.Object[] {$param_ListenerInfo_1, $param_MessageListener_2}, 5126467129635036173L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getTopicInfos()
    public java.util.Collection getTopicInfos()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getTopicInfos_1, null, -2475199111491377027L);
	    return ((java.util.Collection) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of removeListener(ListenerInfo)
    public void removeListener(chat.interfaces.ListenerInfo $param_ListenerInfo_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_removeListener_2, new java.lang.Object[] {$param_ListenerInfo_1}, -1380840971807348269L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of subscribe(TopicInfo, ListenerInfo)
    public chat.interfaces.Topic subscribe(chat.interfaces.TopicInfo $param_TopicInfo_1, chat.interfaces.ListenerInfo $param_ListenerInfo_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_subscribe_3, new java.lang.Object[] {$param_TopicInfo_1, $param_ListenerInfo_2}, 4571213790164827701L);
	    return ((chat.interfaces.Topic) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of unsubscribe(TopicInfo, ListenerInfo)
    public void unsubscribe(chat.interfaces.TopicInfo $param_TopicInfo_1, chat.interfaces.ListenerInfo $param_ListenerInfo_2)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_unsubscribe_4, new java.lang.Object[] {$param_TopicInfo_1, $param_ListenerInfo_2}, -5642571694615417808L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
